spring:
  application:
    name:  gateway
  cloud:
    consul:
      discovery:
        serviceName: ${spring.application.name}
        instanceId: ${spring.application.name}:${random.value}
        healthCheckPath: /actuator/health
        healthCheckInterval: 20s
      host: localhost
      port: 8500
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
      routes:
        - id: continent-lag
          uri: lb://continent-flag
          predicates:
            - Path=/srvcfla/**
        - id: lang-population
          uri: lb://lang-population
          predicates:
            - Path=/srvlapo/**
