spring:
  data:
    mongodb:
      database: country-lang-population
      uri: mongodb://admin:admin@mongo-service:27017/?ssl=false&authSource=admin&authMechanism=SCRAM-SHA-1
  application:
    name:  lang-population
  cloud:
    kubernetes:
      reload:
        enabled: true
#    consul:
#      discovery:
#        serviceName: ${spring.application.name}
#        instanceId: ${spring.application.name}:${random.value}
#        healthCheckPath: /actuator/health
#        healthCheckInterval: 20s
#      host: 192.168.50.1
#      port: 8500
server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: "*"


logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
