
spring:
  application:
    name:  lang-population
  cloud:
    consul:
      discovery:
        serviceName: ${spring.application.name}
        instanceId: ${spring.application.name}:${random.value}
        healthCheckPath: /actuator/health
        healthCheckInterval: 20s
      host: localhost
      port: 8500

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: *
