apiVersion: v1
kind: Service
metadata:
  labels:
    app: continent-flag-service
  name: continent-flag-service
  namespace: spring-cloud
spec:
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  selector:
    app: continent-flag