apiVersion: v1
kind: Service
metadata:
  labels:
    app: lang-population-service
  name: lang-population-service
  namespace: spring-cloud
spec:
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  selector:
    app: lang-population