spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/freemanpolys/spring-config-server-repo.git
          skipSslValidation: true
    consul:
      discovery:
        serviceName: ${spring.application.name}
        instanceId: ${spring.application.name}:${random.value}
        healthCheckPath: /actuator/health
        healthCheckInterval: 20s
      host: 192.168.50.1
      port: 8500
server:
  port: 8800
